[package]
name = "axolotlsay-bun"
description = "JavaScript (Bun) port of axolotlsay"
version = "0.3.0"
license = "MIT"
repository = "https://github.com/axodotdev/axolotlsay-bun"
binaries = ["axolotlsay-bun"]
build-command = ["bash", "build.sh"]

# Config for 'cargo dist'
[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.14.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
